// export const checkAuth = (req, res) => {
//   try {
//     res.status(200).json(req.user);
//   } catch (error) {
//     console.log("Erro na Controladora Auth (checkAuth)", error.message);
//     res.status(500).json({ message: "Erro Interno do Servidor" });
//   }
// };
